# -*- coding: utf-8 -*-
"""dict_conjugaison.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X58y-L5EwlqLuQIssiOYoBXuPF4jwGQK
"""

use = ['직설법(Indicatif)', '조건법(Conditionnel)', '접속법(Subjonctif)', '명령(Imperatif)', '분사(Participe)']
ind = ['현재(Présent)',['복합과거(Passé composé)','반과거(Imparfait)','대과거(Plus-que-parfait)','단순과거(Passé simple)','전과거(Passé antérieur)'],['단순미래(Futur simple)','근접미래(Futur proche)','전미래(Futur antérieur)']]
sub = ['현재(Présent)',['반과거(Imparfait)','대과거(Plus-que-parfait)','과거(Passé)']]
con = ['현재(Présent)',['복합과거 1(Passé première forme)','복합과거 2(Passé deuxième forme)']]
part = ['현재(Présent)','과거(Passé)']

d = {
    "être": [
        [
            # 직설법 (Indicatif)
            [
                # 현재 (Présent)
                "je suis",
                "tu es",
                "il est/elle est",
                "nous sommes",
                "vous êtes",
                "ils sont/elles sont"
            ],
            # 과거
            [
                # 복합과거 (Passé composé)
                [
                    "j'ai été",
                    "tu as été",
                    "il a été/elle a été",
                    "nous avons été",
                    "vous avez été",
                    "ils ont été/elles ont été"
                ],
                # 반과거 (Imparfait)
                [
                    "j'étais",
                    "tu étais",
                    "il était/elle était",
                    "nous étions",
                    "vous étiez",
                    "ils étaient/elles étaient"
                ],
                # 대과거 (Plus-que-parfait)
                [
                    "j'avais été",
                    "tu avais été",
                    "il avait été/elle avait été",
                    "nous avions été",
                    "vous aviez été",
                    "ils avaient été/elles avaient été"
                ],
                # 단순과거 (Passé simple)
                [
                    "je fus",
                    "tu fus",
                    "il fut/elle fut",
                    "nous fûmes",
                    "vous fûtes",
                    "ils furent/elles furent"
                ],
                # 전과거 (Passé antérieur)
                [
                    "j'eus été",
                    "tu eus été",
                    "il eut été/elle eut été",
                    "nous eûmes été",
                    "vous eûtes été",
                    "ils eurent été/elles eurent été"
                ]
            ],
            # 미래
            [
                # 단순미래 (Futur)
                [
                    "je serai",
                    "tu seras",
                    "il sera/elle sera",
                    "nous serons",
                    "vous serez",
                    "ils seront/elles seront"
                ],
                # 근접미래 (Futur proche)
                [
                    "je vais être",
                    "tu vas être",
                    "il va être/elle va être",
                    "nous allons être",
                    "vous allez être",
                    "ils vont être/elles vont être"
                ],
                # 전미래 (Futur antérieur)
                [
                    "j'aurai été",
                    "tu auras été",
                    "il aura été/elle aura été",
                    "nous aurons été",
                    "vous aurez été",
                    "ils auront été/elles auront été"
                ]
            ]
        ],
        [
            # 조건법 (Conditionnel)
            [
                # 현재 (Présent)
                [
                    "je serais",
                    "tu serais",
                    "il serait/elle serait",
                    "nous serions",
                    "vous seriez",
                    "ils seraient/elles seraient"
                ]
            ],
            # 과거
            [
                # 형태 1
                [
                    "j'aurais été",
                    "tu aurais été",
                    "il aurait été/elle aurait été",
                    "nous aurions été",
                    "vous auriez été",
                    "ils auraient été/elles auraient été"
                ],
                # 형태 2
                [
                    "j'eusse été",
                    "tu eusses été",
                    "il eût été/elle eût été",
                    "nous eussions été",
                    "vous eussiez été",
                    "ils eussent été/elles eussent été"
                ]
            ]
        ],
        [
            # 접속법 (Subjonctif)
            [
                # 현재 (Présent)
                [
                    "que je sois",
                    "que tu sois",
                    "qu'il soit/qu'elle soit",
                    "que nous soyons",
                    "que vous soyez",
                    "qu'ils soient/qu'elles soient"
                ]
            ],
            # 과거
            [
                # 반과거 (Imparfait)
                [
                    "que je fusse",
                    "que tu fusses",
                    "qu'il fût/qu'elle fût",
                    "que nous fussions",
                    "que vous fussiez",
                    "qu'ils fussent/qu'elles fussent"
                ],
                # 대과거 (Plus-que-parfait)
                [
                    "que j'eusse été",
                    "que tu eusses été",
                    "qu'il eût été/qu'elle eût été",
                    "que nous eussions été",
                    "que vous eussiez été",
                    "qu'ils eussent été/qu'elles eussent été"
                ],
                # 과거 (Passé)
                [
                    "que j'aie été",
                    "que tu aies été",
                    "qu'il ait été/qu'elle ait été",
                    "que nous ayons été",
                    "que vous ayez été",
                    "qu'ils aient été/qu'elles aient été"
                ]
            ]
        ],
        [
            # 명령법 (Impératif)

                # 현재 (Présent)

                    "(tu) sois",
                    "(nous) soyons",
                    "(vous) soyez"


        ],
        [
            # 분사 (Participe)
            [
                # 현재 (Présent)
                "étant"
            ],
            [
                # 과거 (Passé)
                [
                    "été",
                    "étés",
                    "étée",
                    "étées"
                ]
            ]
        ]
    ],
    "avoir": [
        [
            # 직설법 (Indicatif)
            [
                # 현재 (Présent)
                "j'ai",
                "tu as",
                "il a/elle a",
                "nous avons",
                "vous avez",
                "ils ont/elles ont"
            ],
            # 과거
            [
                # 복합과거 (Passé composé)
                [
                    "j'ai eu",
                    "tu as eu",
                    "il a eu/elle a eu",
                    "nous avons eu",
                    "vous avez eu",
                    "ils ont eu/elles ont eu"
                ],
                # 반과거 (Imparfait)
                [
                    "j'avais",
                    "tu avais",
                    "il avait/elle avait",
                    "nous avions",
                    "vous aviez",
                    "ils avaient/elles avaient"
                ],
                # 대과거 (Plus-que-parfait)
                [
                    "j'avais eu",
                    "tu avais eu",
                    "il avait eu/elle avait eu",
                    "nous avions eu",
                    "vous aviez eu",
                    "ils avaient eu/elles avaient eu"
                ],
                # 단순과거 (Passé simple)
                [
                    "j'eus",
                    "tu eus",
                    "il eut/elle eut",
                    "nous eûmes",
                    "vous eûtes",
                    "ils eurent/elles eurent"
                ],
                # 전과거 (Passé antérieur)
                [
                    "j'eus eu",
                    "tu eus eu",
                    "il eut eu/elle eut eu",
                    "nous eûmes eu",
                    "vous eûtes eu",
                    "ils eurent eu/elles eurent eu"
                ]
            ],
            # 미래
            [
                # 단순미래 (Futur)
                [
                    "j'aurai",
                    "tu auras",
                    "il aura/elle aura",
                    "nous aurons",
                    "vous aurez",
                    "ils auront/elles auront"
                ],
                # 근접미래 (Futur proche)
                [
                    "je vais avoir",
                    "tu vas avoir",
                    "il va avoir/elle va avoir",
                    "nous allons avoir",
                    "vous allez avoir",
                    "ils vont avoir/elles vont avoir"
                ],
                # 전미래 (Futur antérieur)
                [
                    "j'aurai eu",
                    "tu auras eu",
                    "il aura eu/elle aura eu",
                    "nous aurons eu",
                    "vous aurez eu",
                    "ils auront eu/elles auront eu"
                ]
            ]
        ],
        [
            # 조건법 (Conditionnel)
            [
                # 현재 (Présent)

                    "j'aurais",
                    "tu aurais",
                    "il aurait/elle aurait",
                    "nous aurions",
                    "vous auriez",
                    "ils auraient/elles auraient"

            ],
            # 과거
            [
                # 형태 1
                [
                    "j'aurais eu",
                    "tu aurais eu",
                    "il aurait eu/elle aurait eu",
                    "nous aurions eu",
                    "vous auriez eu",
                    "ils auraient eu/elles auraient eu"
                ],
                # 형태 2
                [
                    "j'eusse eu",
                    "tu eusses eu",
                    "il eût eu/elle eût eu",
                    "nous eussions eu",
                    "vous eussiez eu",
                    "ils eussent eu/elles eussent eu"
                ]
            ]
        ],
        [
            # 접속법 (Subjonctif)
            [
                # 현재 (Présent)

                    "que j'aie",
                    "que tu aies",
                    "qu'il ait/qu'elle ait",
                    "que nous ayons",
                    "que vous ayez",
                    "qu'ils aient/qu'elles aient"

            ],
            # 과거
            [
                # 반과거 (Imparfait)
                [
                    "que j'eusse",
                    "que tu eusses",
                    "qu'il eût/qu'elle eût",
                    "que nous eussions",
                    "que vous eussiez",
                    "qu'ils eussent/qu'elles eussent"
                ],
                # 대과거 (Plus-que-parfait)
                [
                    "que j'eusse eu",
                    "que tu eusses eu",
                    "qu'il eût eu/qu'elle eût eu",
                    "que nous eussions eu",
                    "que vous eussiez eu",
                    "qu'ils eussent eu/qu'elles eussent eu"
                ],
                # 과거 (Passé)
                [
                    "que j'aie eu",
                    "que tu aies eu",
                    "qu'il ait eu/qu'elle ait eu",
                    "que nous ayons eu",
                    "que vous ayez eu",
                    "qu'ils aient eu/qu'elles aient eu"
                ]
            ]
        ],
        [
            # 명령법 (Impératif)

                # 현재 (Présent)

                    "(tu) aie",
                    "(nous) ayons",
                    "(vous) ayez"


        ],
        [
            # 분사 (Participe)
            [
                # 현재 (Présent)
                "ayant"
            ],
            [
                # 과거 (Passé)

                    "eu",
                    "eus",
                    "eue",
                    "eues"

            ]
        ]
    ],

    "faire": [
        [
            # 직설법 (Indicatif)
            [
                # 현재 (Présent)
                "je fais",
                "tu fais",
                "il fait/elle fait",
                "nous faisons",
                "vous faites",
                "ils font/elles font"
            ],
            # 과거
            [
                # 복합과거 (Passé composé)
                [
                    "j'ai fait",
                    "tu as fait",
                    "il a fait/elle a fait",
                    "nous avons fait",
                    "vous avez fait",
                    "ils ont fait/elles ont fait"
                ],
                # 반과거 (Imparfait)
                [
                    "je faisais",
                    "tu faisais",
                    "il faisait/elle faisait",
                    "nous faisions",
                    "vous faisiez",
                    "ils faisaient/elles faisaient"
                ],
                # 대과거 (Plus-que-parfait)
                [
                    "j'avais fait",
                    "tu avais fait",
                    "il avait fait/elle avait fait",
                    "nous avions fait",
                    "vous aviez fait",
                    "ils avaient fait/elles avaient fait"
                ],
                # 단순과거 (Passé simple)
                [
                    "je fis",
                    "tu fis",
                    "il fit/elle fit",
                    "nous fîmes",
                    "vous fîtes",
                    "ils firent/elles firent"
                ],
                # 전과거 (Passé antérieur)
                [
                    "j'eus fait",
                    "tu eus fait",
                    "il eut fait/elle eut fait",
                    "nous eûmes fait",
                    "vous eûtes fait",
                    "ils eurent fait/elles eurent fait"
                ]
            ],
            # 미래
            [
                # 단순미래 (Futur)
                [
                    "je ferai",
                    "tu feras",
                    "il fera/elle fera",
                    "nous ferons",
                    "vous ferez",
                    "ils feront/elles feront"
                ],
                # 근접미래 (Futur proche)
                [
                    "je vais faire",
                    "tu vas faire",
                    "il va faire/elle va faire",
                    "nous allons faire",
                    "vous allez faire",
                    "ils vont faire/elles vont faire"
                ],
                # 전미래 (Futur antérieur)
                [
                    "j'aurai fait",
                    "tu auras fait",
                    "il aura fait/elle aura fait",
                    "nous aurons fait",
                    "vous aurez fait",
                    "ils auront fait/elles auront fait"
                ]
            ]
        ],
        [
            # 조건법 (Conditionnel)
            [
                # 현재 (Présent)
                [
                    "je ferais",
                    "tu ferais",
                    "il ferait/elle ferait",
                    "nous ferions",
                    "vous feriez",
                    "ils feraient/elles feraient"
                ]
            ],
            # 과거
            [
                # 형태 1
                [
                    "j'aurais fait",
                    "tu aurais fait",
                    "il aurait fait/elle aurait fait",
                    "nous aurions fait",
                    "vous auriez fait",
                    "ils auraient fait/elles auraient fait"
                ],
                # 형태 2
                [
                    "j'eusse fait",
                    "tu eusses fait",
                    "il eût fait/elle eût fait",
                    "nous eussions fait",
                    "vous eussiez fait",
                    "ils eussent fait/elles eussent fait"
                ]
            ]
        ],
        [
            # 접속법 (Subjonctif)
            [
                # 현재 (Présent)

                    "que je fasse",
                    "que tu fasses",
                    "qu'il fasse/qu'elle fasse",
                    "que nous fassions",
                    "que vous fassiez",
                    "qu'ils fassent/qu'elles fassent"

            ],
            # 과거
            [
                # 반과거 (Imparfait)
                [
                    "que je fisse",
                    "que tu fisses",
                    "qu'il fît/qu'elle fît",
                    "que nous fissions",
                    "que vous fissiez",
                    "qu'ils fissent/qu'elles fissent"
                ],
                # 대과거 (Plus-que-parfait)
                [
                    "que j'eusse fait",
                    "que tu eusses fait",
                    "qu'il eût fait/qu'elle eût fait",
                    "que nous eussions fait",
                    "que vous eussiez fait",
                    "qu'ils eussent fait/qu'elles eussent fait"
                ],
                # 과거 (Passé)
                [
                    "que j'aie fait",
                    "que tu aies fait",
                    "qu'il ait fait/qu'elle ait fait",
                    "que nous ayons fait",
                    "que vous ayez fait",
                    "qu'ils aient fait/qu'elles aient fait"
                ]
            ]
        ],
        [
            # 명령법 (Impératif)
            [
                # 현재 (Présent)

                    "(tu) fais",
                    "(nous) faisons",
                    "(vous) faites"

            ]
        ],
        [
            # 분사 (Participe)
            [
                # 현재 (Présent)
                "faisant"
            ],
            [
                # 과거 (Passé)

                    "fait",
                    "faits",
                    "faite",
                    "faites"

            ]
        ]
    ], "dire": [
        [
            # 직설법 (Indicatif)
            [
                # 현재 (Présent)
                "je dis",
                "tu dis",
                "il dit/elle dit",
                "nous disons",
                "vous dites",
                "ils disent/elles disent"
            ],
            # 과거
            [
                # 복합과거 (Passé composé)
                [
                    "j'ai dit",
                    "tu as dit",
                    "il a dit/elle a dit",
                    "nous avons dit",
                    "vous avez dit",
                    "ils ont dit/elles ont dit"
                ],
                # 반과거 (Imparfait)
                [
                    "je disais",
                    "tu disais",
                    "il disait/elle disait",
                    "nous disions",
                    "vous disiez",
                    "ils disaient/elles disaient"
                ],
                # 대과거 (Plus-que-parfait)
                [
                    "j'avais dit",
                    "tu avais dit",
                    "il avait dit/elle avait dit",
                    "nous avions dit",
                    "vous aviez dit",
                    "ils avaient dit/elles avaient dit"
                ],
                # 단순과거 (Passé simple)
                [
                    "je dis",
                    "tu dis",
                    "il dit/elle dit",
                    "nous dîmes",
                    "vous dîtes",
                    "ils dirent/elles dirent"
                ],
                # 전과거 (Passé antérieur)
                [
                    "j'eus dit",
                    "tu eus dit",
                    "il eut dit/elle eut dit",
                    "nous eûmes dit",
                    "vous eûtes dit",
                    "ils eurent dit/elles eurent dit"
                ]
            ],
            # 미래
            [
                # 단순미래 (Futur)
                [
                    "je dirai",
                    "tu diras",
                    "il dira/elle dira",
                    "nous dirons",
                    "vous direz",
                    "ils diront/elles diront"
                ],
                # 근접미래 (Futur proche)
                [
                    "je vais dire",
                    "tu vas dire",
                    "il va dire/elle va dire",
                    "nous allons dire",
                    "vous allez dizer",
                    "ils vont dire/elles vont dire"
                ],
                # 전미래 (Futur antérieur)
                [
                    "j'aurai dit",
                    "tu auras dit",
                    "il aura dit/elle aura dit",
                    "nous aurons dit",
                    "vous aurez dit",
                    "ils auront dit/elles auront dit"
                ]
            ]
        ],
        [
            # 조건법 (Conditionnel)
            [
                # 현재 (Présent)

                    "je dirais",
                    "tu dirais",
                    "il dirait/elle dirait",
                    "nous dirions",
                    "vous diriez",
                    "ils diraient/elles diraient"

            ],
            # 과거
            [
                # 형태 1
                [
                    "j'aurais dit",
                    "tu aurais dit",
                    "il aurait dit/elle aurait dit",
                    "nous aurions dit",
                    "vous auriez dit",
                    "ils auraient dit/elles auraient dit"
                ],
                # 형태 2
                [
                    "j'eusse dit",
                    "tu eusses dit",
                    "il eût dit/elle eût dit",
                    "nous eussions dit",
                    "vous eussiez dit",
                    "ils eussent dit/elles eussent dit"
                ]
            ]
        ],
        [
            # 접속법 (Subjonctif)
            [
                # 현재 (Présent)

                    "que je dise",
                    "que tu dises",
                    "qu'il dise/qu'elle dise",
                    "que nous disions",
                    "que vous disiez",
                    "qu'ils disent/qu'elles disent"

            ],
            # 과거
            [
                # 반과거 (Imparfait)
                [
                    "que je disse",
                    "que tu disses",
                    "qu'il dît/qu'elle dît",
                    "que nous dissions",
                    "que vous dissiez",
                    "qu'ils dissent/qu'elles dissent"
                ],
                # 대과거 (Plus-que-parfait)
                [
                    "que j'eusse dit",
                    "que tu eusses dit",
                    "qu'il eût dit/qu'elle eût dit",
                    "que nous eussions dit",
                    "que vous eussiez dit",
                    "qu'ils eussent dit/qu'elles eussent dit"
                ],
                # 과거 (Passé)
                [
                    "que j'aie dit",
                    "que tu aies dit",
                    "qu'il ait dit/qu'elle ait dit",
                    "que nous ayons dit",
                    "que vous ayez dit",
                    "qu'ils aient dit/qu'elles aient dit"
                ]
            ]
        ],
        [
            # 명령법 (Impératif)

                # 현재 (Présent)

                    "(tu) dis",
                    "(nous) disons",
                    "(vous) dites"


        ],
        [
            # 분사 (Participe)
            [
                # 현재 (Présent)
                "disant"
            ],
            [
                # 과거 (Passé)

                    "dit",
                    "dits",
                    "dite",
                    "dites"

            ]
        ]
    ],
    "pouvoir": [
        [
            # 직설법 (Indicatif)
            [
                # 현재 (Présent)
                "je peux",
                "tu peux",
                "il peut/elle peut",
                "nous pouvons",
                "vous pouvez",
                "ils peuvent/elles peuvent"
            ],
            # 과거
            [
                # 복합과거 (Passé composé)
                [
                    "j'ai pu",
                    "tu as pu",
                    "il a pu/elle a pu",
                    "nous avons pu",
                    "vous avez pu",
                    "ils ont pu/elles ont pu"
                ],
                # 반과거 (Imparfait)
                [
                    "je pouvais",
                    "tu pouvais",
                    "il pouvait/elle pouvait",
                    "nous pouvions",
                    "vous pouviez",
                    "ils pouvaient/elles pouvaient"
                ],
                # 대과거 (Plus-que-parfait)
                [
                    "j'avais pu",
                    "tu avais pu",
                    "il avait pu/elle avait pu",
                    "nous avions pu",
                    "vous aviez pu",
                    "ils avaient pu/elles avaient pu"
                ],
                # 단순과거 (Passé simple)
                [
                    "je pus",
                    "tu pus",
                    "il put/elle put",
                    "nous pûmes",
                    "vous pûtes",
                    "ils purent/elles purent"
                ],
                # 전과거 (Passé antérieur)
                [
                    "j'eus pu",
                    "tu eus pu",
                    "il eut pu/elle eut pu",
                    "nous eûmes pu",
                    "vous eûtes pu",
                    "ils eurent pu/elles eurent pu"
                ]
            ],
            # 미래
            [
                # 단순미래 (Futur)
                [
                    "je pourrai",
                    "tu pourras",
                    "il pourra/elle pourra",
                    "nous pourrons",
                    "vous pourrez",
                    "ils pourront/elles pourront"
                ],
                # 근접미래 (Futur proche)
                [
                    "je vais pouvoir",
                    "tu vas pouvoir",
                    "il va pouvoir/elle va pouvoir",
                    "nous allons pouvoir",
                    "vous allez pouvoir",
                    "ils vont pouvoir/elles vont pouvoir"
                ],
                # 전미래 (Futur antérieur)
                [
                    "j'aurai pu",
                    "tu auras pu",
                    "il aura pu/elle aura pu",
                    "nous aurons pu",
                    "vous aurez pu",
                    "ils auront pu/elles auront pu"
                ]
            ]
        ],
        [
            # 조건법 (Conditionnel)
            [
                # 현재 (Présent)

                    "je pourrais",
                    "tu pourrais",
                    "il pourrait/elle pourrait",
                    "nous pourrions",
                    "vous pourriez",
                    "ils pourraient/elles pourraient"

            ],
            # 과거
            [
                # 형태 1
                [
                    "j'aurais pu",
                    "tu aurais pu",
                    "il aurait pu/elle aurait pu",
                    "nous aurions pu",
                    "vous auriez pu",
                    "ils auraient pu/elles auraient pu"
                ],
                # 형태 2
                [
                    "j'eusse pu",
                    "tu eusses pu",
                    "il eût pu/elle eût pu",
                    "nous eussions pu",
                    "vous eussiez pu",
                    "ils eussent pu/elles eussent pu"
                ]
            ]
        ],
        [
            # 접속법 (Subjonctif)
            [
                # 현재 (Présent)

                    "que je puisse",
                    "que tu puisses",
                    "qu'il puisse/qu'elle puisse",
                    "que nous puissions",
                    "que vous puissiez",
                    "qu'ils puissent/qu'elles puissent"

            ],
            # 과거
            [
                # 반과거 (Imparfait)
                [
                    "que je pusse",
                    "que tu pusses",
                    "qu'il pût/qu'elle pût",
                    "que nous pussions",
                    "que vous pussiez",
                    "qu'ils pussent/qu'elles pussent"
                ],
                # 대과거 (Plus-que-parfait)
                [
                    "que j'eusse pu",
                    "que tu eusses pu",
                    "qu'il eût pu/qu'elle eût pu",
                    "que nous eussions pu",
                    "que vous eussiez pu",
                    "qu'ils eussent pu/qu'elles eussent pu"
                ],
                # 과거 (Passé)
                [
                    "que j'aie pu",
                    "que tu aies pu",
                    "qu'il ait pu/qu'elle ait pu",
                    "que nous ayons pu",
                    "que vous ayez pu",
                    "qu'ils aient pu/qu'elles aient pu"
                ]
            ]
        ],
        [
            # 명령법 (Impératif)

                # 현재 (Présent)

                    "(tu) peux",
                    "(nous) puissions",
                    "(vous) puissiez"


        ],
        [
            # 분사 (Participe)
            [
                # 현재 (Présent)
                "pouvant"
            ],
            [
                # 과거 (Passé)

                    "pu"

            ]
        ]
    ],
     "aller": [
        [
            # 직설법 (Indicatif)
            [
                # 현재 (Présent)
                [
                    "je vais",
                    "tu vas",
                    "il va/elle va",
                    "nous allons",
                    "vous allez",
                    "ils vont/elles vont"
                ]
            ],
            # 과거
            [
                # 복합과거 (Passé composé)
                [
                    "je suis allé(e)",
                    "tu es allé(e)",
                    "il est allé/elle est allée",
                    "nous sommes allé(e)s",
                    "vous êtes allé(e)(s)",
                    "ils sont allés/elles sont allées"
                ],
                # 반과거 (Imparfait)
                [
                    "j'allais",
                    "tu allais",
                    "il allait/elle allait",
                    "nous allions",
                    "vous alliez",
                    "ils allaient/elles allaient"
                ],
                # 대과거 (Plus-que-parfait)
                [
                    "j'étais allé(e)",
                    "tu étais allé(e)",
                    "il était allé/elle était allée",
                    "nous étions allé(e)s",
                    "vous étiez allé(e)(s)",
                    "ils étaient allés/elles étaient allées"
                ],
                # 단순과거 (Passé simple)
                [
                    "j'allai",
                    "tu allas",
                    "il alla/elle alla",
                    "nous allâmes",
                    "vous allâtes",
                    "ils allèrent/elles allèrent"
                ],
                # 전과거 (Passé antérieur)
                [
                    "je fus allé(e)",
                    "tu fus allé(e)",
                    "il fut allé/elle fut allée",
                    "nous fûmes allé(e)s",
                    "vous fûtes allé(e)(s)",
                    "ils furent allés/elles furent allées"
                ]
            ],
            # 미래
            [
                # 단순미래 (Futur)
                [
                    "j'irai",
                    "tu iras",
                    "il ira/elle ira",
                    "nous irons",
                    "vous irez",
                    "ils iront/elles iront"
                ],
                # 근접미래 (Futur proche)
                [
                    "je vais aller",
                    "tu vas aller",
                    "il va aller/elle va aller",
                    "nous allons aller",
                    "vous allez aller",
                    "ils vont aller/elles vont aller"
                ],
                # 전미래 (Futur antérieur)
                [
                    "je serai allé(e)",
                    "tu seras allé(e)",
                    "il sera allé/elle sera allée",
                    "nous serons allé(e)s",
                    "vous serez allé(e)(s)",
                    "ils seront allés/elles seront allées"
                ]
            ]
        ],
        [
            # 조건법 (Conditionnel)
            [
                # 현재 (Présent)

                    "j'irais",
                    "tu irais",
                    "il irait/elle irait",
                    "nous irions",
                    "vous iriez",
                    "ils iraient/elles iraient"

            ],
            # 과거
            [
                # 형태 1
                [
                    "je serais allé(e)",
                    "tu serais allé(e)",
                    "il serait allé/elle serait allée",
                    "nous serions allé(e)s",
                    "vous seriez allé(e)(s)",
                    "ils seraient allés/elles seraient allées"
                ],
                # 형태 2
                [
                    "je fusse allé(e)",
                    "tu fusses allé(e)",
                    "il fût allé/elle fût allée",
                    "nous fussions allé(e)s",
                    "vous fussiez allé(e)(s)",
                    "ils fussent allés/elles fussent allées"
                ]
            ]
        ],
        [
            # 접속법 (Subjonctif)
            [
                # 현재 (Présent)

                    "que j'aille",
                    "que tu ailles",
                    "qu'il aille/qu'elle aille",
                    "que nous allions",
                    "que vous alliez",
                    "qu'ils aillent/qu'elles aillent"

            ],
            # 과거
            [
                # 반과거 (Imparfait)
                [
                    "que j'allasse",
                    "que tu allasses",
                    "qu'il allât/qu'elle allât",
                    "que nous allassions",
                    "que vous allassiez",
                    "qu'ils allassent/qu'elles allassent"
                ],
                # 대과거 (Plus-que-parfait)
                [
                    "que je fusse allé(e)",
                    "que tu fusses allé(e)",
                    "qu'il fût allé/qu'elle fût allée",
                    "que nous fussions allé(e)s",
                    "que vous fussiez allé(e)(s)",
                    "qu'ils fussent allés/qu'elles fussent allées"
                ],
                # 과거 (Passé)
                [
                    "que je sois allé(e)",
                    "que tu sois allé(e)",
                    "qu'il soit allé/qu'elle soit allée",
                    "que nous soyons allé(e)s",
                    "que vous soyez allé(e)(s)",
                    "qu'ils soient allés/qu'elles soient allées"
                ]
            ]
        ],
        [
            # 명령법 (Impératif)

                # 현재 (Présent)

                    "(tu) va",
                    "(nous) allons",
                    "(vous) allez"


        ],
        [
            # 분사 (Participe)
            [
                # 현재 (Présent)
                "allant"
            ],
            [
                # 과거 (Passé)

                    "allé",
                    "allés",
                    "allée",
                    "allées"

            ]
        ]
    ],
    "voir": [
        [
            # 직설법 (Indicatif)
            [
                # 현재 (Présent)

                    "je vois",
                    "tu vois",
                    "il voit/elle voit",
                    "nous voyons",
                    "vous voyez",
                    "ils voient/elles voient"

            ],
            # 과거
            [
                # 복합과거 (Passé composé)
                [
                    "j'ai vu",
                    "tu as vu",
                    "il a vu/elle a vu",
                    "nous avons vu",
                    "vous avez vu",
                    "ils ont vu/elles ont vu"
                ],
                # 반과거 (Imparfait)
                [
                    "je voyais",
                    "tu voyais",
                    "il voyait/elle voyait",
                    "nous voyions",
                    "vous voyiez",
                    "ils voyaient/elles voyaient"
                ],
                # 대과거 (Plus-que-parfait)
                [
                    "j'avais vu",
                    "tu avais vu",
                    "il avait vu/elle avait vu",
                    "nous avions vu",
                    "vous aviez vu",
                    "ils avaient vu/elles avaient vu"
                ],
                # 단순과거 (Passé simple)
                [
                    "je vis",
                    "tu vis",
                    "il vit/elle vit",
                    "nous vîmes",
                    "vous vîtes",
                    "ils virent/elles virent"
                ],
                # 전과거 (Passé antérieur)
                [
                    "j'eus vu",
                    "tu eus vu",
                    "il eut vu/elle eut vu",
                    "nous eûmes vu",
                    "vous eûtes vu",
                    "ils eurent vu/elles eurent vu"
                ]
            ],
            # 미래
            [
                # 단순미래 (Futur)
                [
                    "je verrai",
                    "tu verras",
                    "il verra/elle verra",
                    "nous verrons",
                    "vous verrez",
                    "ils verront/elles verront"
                ],
                # 근접미래 (Futur proche)
                [
                    "je vais voir",
                    "tu vas voir",
                    "il va voir/elle va voir",
                    "nous allons voir",
                    "vous allez voir",
                    "ils vont voir/elles vont voir"
                ],
                # 전미래 (Futur antérieur)
                [
                    "j'aurai vu",
                    "tu auras vu",
                    "il aura vu/elle aura vu",
                    "nous aurons vu",
                    "vous aurez vu",
                    "ils auront vu/elles auront vu"
                ]
            ]
        ],
        [
            # 조건법 (Conditionnel)
            [
                # 현재 (Présent)

                    "je verrais",
                    "tu verrais",
                    "il verrait/elle verrait",
                    "nous verrions",
                    "vous verriez",
                    "ils verraient/elles verraient"

            ],
            # 과거
            [
                # 형태 1
                [
                    "j'aurais vu",
                    "tu aurais vu",
                    "il aurait vu/elle aurait vu",
                    "nous aurions vu",
                    "vous auriez vu",
                    "ils auraient vu/elles auraient vu"
                ],
                # 형태 2
                [
                    "j'eusse vu",
                    "tu eusses vu",
                    "il eût vu/elle eût vu",
                    "nous eussions vu",
                    "vous eussiez vu",
                    "ils eussent vu/elles eussent vu"
                ]
            ]
        ],
        [
            # 접속법 (Subjonctif)
            [
                # 현재 (Présent)

                    "que je voie",
                    "que tu voies",
                    "qu'il voie/qu'elle voie",
                    "que nous voyions",
                    "que vous voyiez",
                    "qu'ils voient/qu'elles voient"

            ],
            # 과거
            [
                # 반과거 (Imparfait)
                [
                    "que je visse",
                    "que tu visses",
                    "qu'il vît/qu'elle vît",
                    "que nous vissions",
                    "que vous vissiez",
                    "qu'ils vissent/qu'elles vissent"
                ],
                # 대과거 (Plus-que-parfait)
                [
                    "que j'eusse vu",
                    "que tu eusses vu",
                    "qu'il eût vu/qu'elle eût vu",
                    "que nous eussions vu",
                    "que vous eussiez vu",
                    "qu'ils eussent vu/qu'elles eussent vu"
                ],
                # 과거 (Passé)
                [
                    "que j'aie vu",
                    "que tu aies vu",
                    "qu'il ait vu/qu'elle ait vu",
                    "que nous ayons vu",
                    "que vous ayez vu",
                    "qu'ils aient vu/qu'elles aient vu"
                ]
            ]
        ],
        [
            # 명령법 (Impératif)

                # 현재 (Présent)

                    "(tu) vois",
                    "(nous) voyons",
                    "(vous) voyez"


        ],
        [
            # 분사 (Participe)
            [
                # 현재 (Présent)
                "voyant"
            ],
            [
                # 과거 (Passé)

                    "vu",
                    "vus",
                    "vue",
                    "vues"

            ]
        ]
    ],
     "savoir": [
        [
            # 직설법 (Indicatif)
            [
                # 현재 (Présent)

                    "je sais",
                    "tu sais",
                    "il sait/elle sait",
                    "nous savons",
                    "vous savez",
                    "ils savent/elles savent"

            ],
            # 과거
            [
                # 복합과거 (Passé composé)
                [
                    "j'ai su",
                    "tu as su",
                    "il a su/elle a su",
                    "nous avons su",
                    "vous avez su",
                    "ils ont su/elles ont su"
                ],
                # 반과거 (Imparfait)
                [
                    "je savais",
                    "tu savais",
                    "il savait/elle savait",
                    "nous savions",
                    "vous saviez",
                    "ils savaient/elles savaient"
                ],
                # 대과거 (Plus-que-parfait)
                [
                    "j'avais su",
                    "tu avais su",
                    "il avait su/elle avait su",
                    "nous avions su",
                    "vous aviez su",
                    "ils avaient su/elles avaient su"
                ],
                # 단순과거 (Passé simple)
                [
                    "je sus",
                    "tu sus",
                    "il sut/elle sut",
                    "nous sûmes",
                    "vous sûtes",
                    "ils surent/elles surent"
                ],
                # 전과거 (Passé antérieur)
                [
                    "j'eus su",
                    "tu eus su",
                    "il eut su/elle eut su",
                    "nous eûmes su",
                    "vous eûtes su",
                    "ils eurent su/elles eurent su"
                ]
            ],
            # 미래
            [
                # 단순미래 (Futur)
                [
                    "je saurai",
                    "tu sauras",
                    "il saura/elle saura",
                    "nous saurons",
                    "vous saurez",
                    "ils sauront/elles sauront"
                ],
                # 근접미래 (Futur proche)
                [
                    "je vais savoir",
                    "tu vas savoir",
                    "il va savoir/elle va savoir",
                    "nous allons savoir",
                    "vous allez savoir",
                    "ils vont savoir/elles vont savoir"
                ],
                # 전미래 (Futur antérieur)
                [
                    "j'aurai su",
                    "tu auras su",
                    "il aura su/elle aura su",
                    "nous aurons su",
                    "vous aurez su",
                    "ils auront su/elles auront su"
                ]
            ]
        ],
        [
            # 조건법 (Conditionnel)
            [
                # 현재 (Présent)

                    "je saurais",
                    "tu saurais",
                    "il saurait/elle saurait",
                    "nous saurions",
                    "vous sauriez",
                    "ils sauraient/elles sauraient"

            ],
            # 과거
            [
                # 형태 1
                [
                    "j'aurais su",
                    "tu aurais su",
                    "il aurait su/elle aurait su",
                    "nous aurions su",
                    "vous auriez su",
                    "ils auraient su/elles auraient su"
                ],
                # 형태 2
                [
                    "j'eusse su",
                    "tu eusses su",
                    "il eût su/elle eût su",
                    "nous eussions su",
                    "vous eussiez su",
                    "ils eussent su/elles eussent su"
                ]
            ]
        ],
        [
            # 접속법 (Subjonctif)
            [
                # 현재 (Présent)

                    "que je sache",
                    "que tu saches",
                    "qu'il sache/qu'elle sache",
                    "que nous sachions",
                    "que vous sachiez",
                    "qu'ils sachent/qu'elles sachent"

            ],
            # 과거
            [
                # 반과거 (Imparfait)
                [
                    "que je susse",
                    "que tu susses",
                    "qu'il sût/qu'elle sût",
                    "que nous sussions",
                    "que vous sussiez",
                    "qu'ils sussent/qu'elles sussent"
                ],
                # 대과거 (Plus-que-parfait)
                [
                    "que j'eusse su",
                    "que tu eusses su",
                    "qu'il eût su/qu'elle eût su",
                    "que nous eussions su",
                    "que vous eussiez su",
                    "qu'ils eussent su/qu'elles eussent su"
                ],
                # 과거 (Passé)
                [
                    "que j'aie su",
                    "que tu aies su",
                    "qu'il ait su/qu'elle ait su",
                    "que nous ayons su",
                    "que vous ayez su",
                    "qu'ils aient su/qu'elles aient su"
                ]
            ]
        ],
        [
            # 명령법 (Impératif)

                # 현재 (Présent)

                    "(tu) sache",
                    "(nous) sachons",
                    "(vous) sachez"


        ],
        [
            # 분사 (Participe)
            [
                # 현재 (Présent)
                "sachant"
            ],
            [
                # 과거 (Passé)

                    "su",
                    "sue",
                    "sus",
                    "sues"

            ]
        ]
    ],
    "vouloir": [
        [
            # 직설법 (Indicatif)
            [
                # 현재 (Présent)

                    "je veux",
                    "tu veux",
                    "il veut/elle veut",
                    "nous voulons",
                    "vous voulez",
                    "ils veulent/elles veulent"

            ],
            # 과거
            [
                # 복합과거 (Passé composé)
                [
                    "j'ai voulu",
                    "tu as voulu",
                    "il a voulu/elle a voulu",
                    "nous avons voulu",
                    "vous avez voulu",
                    "ils ont voulu/elles ont voulu"
                ],
                # 반과거 (Imparfait)
                [
                    "je voulais",
                    "tu voulais",
                    "il voulait/elle voulait",
                    "nous voulions",
                    "vous vouliez",
                    "ils voulaient/elles voulaient"
                ],
                # 대과거 (Plus-que-parfait)
                [
                    "j'avais voulu",
                    "tu avais voulu",
                    "il avait voulu/elle avait voulu",
                    "nous avions voulu",
                    "vous aviez voulu",
                    "ils avaient voulu/elles avaient voulu"
                ],
                # 단순과거 (Passé simple)
                [
                    "je voulus",
                    "tu voulus",
                    "il voulut/elle voulut",
                    "nous voulûmes",
                    "vous voulûtes",
                    "ils voulurent/elles voulurent"
                ],
                # 전과거 (Passé antérieur)
                [
                    "j'eus voulu",
                    "tu eus voulu",
                    "il eut voulu/elle eut voulu",
                    "nous eûmes voulu",
                    "vous eûtes voulu",
                    "ils eurent voulu/elles eurent voulu"
                ]
            ],
            # 미래
            [
                # 단순미래 (Futur)
                [
                    "je voudrai",
                    "tu voudras",
                    "il voudra/elle voudra",
                    "nous voudrons",
                    "vous voudrez",
                    "ils voudront/elles voudront"
                ],
                # 근접미래 (Futur proche)
                [
                    "je vais vouloir",
                    "tu vas vouloir",
                    "il va vouloir/elle va vouloir",
                    "nous allons vouloir",
                    "vous allez vouloir",
                    "ils vont vouloir/elles vont vouloir"
                ],
                # 전미래 (Futur antérieur)
                [
                    "j'aurai voulu",
                    "tu auras voulu",
                    "il aura voulu/elle aura voulu",
                    "nous aurons voulu",
                    "vous aurez voulu",
                    "ils auront voulu/elles auront voulu"
                ]
            ]
        ],
        [
            # 조건법 (Conditionnel)
            [
                # 현재 (Présent)

                    "je voudrais",
                    "tu voudrais",
                    "il voudrait/elle voudrait",
                    "nous voudrions",
                    "vous voudriez",
                    "ils voudraient/elles voudraient"

            ],
            # 과거
            [
                # 형태 1
                [
                    "j'aurais voulu",
                    "tu aurais voulu",
                    "il aurait voulu/elle aurait voulu",
                    "nous aurions voulu",
                    "vous auriez voulu",
                    "ils auraient voulu/elles auraient voulu"
                ],
                # 형태 2
                [
                    "j'eusse voulu",
                    "tu eusses voulu",
                    "il eût voulu/elle eût voulu",
                    "nous eussions voulu",
                    "vous eussiez voulu",
                    "ils eussent voulu/elles eussent voulu"
                ]
            ]
        ],
        [
            # 접속법 (Subjonctif)
            [
                # 현재 (Présent)

                    "que je veuille",
                    "que tu veuilles",
                    "qu'il veuille/qu'elle veuille",
                    "que nous voulions",
                    "que vous vouliez",
                    "qu'ils veuillent/qu'elles veuillent"

            ],
            # 과거
            [
                # 반과거 (Imparfait)
                [
                    "que je voulusse",
                    "que tu voulusses",
                    "qu'il voulût/qu'elle voulût",
                    "que nous voulussions",
                    "que vous voulussiez",
                    "qu'ils voulussent/qu'elles voulussent"
                ],
                # 대과거 (Plus-que-parfait)
                [
                    "que j'eusse voulu",
                    "que tu eusses voulu",
                    "qu'il eût voulu/qu'elle eût voulu",
                    "que nous eussions voulu",
                    "que vous eussiez voulu",
                    "qu'ils eussent voulu/qu'elles eussent voulu"
                ],
                # 과거 (Passé)
                [
                    "que j'aie voulu",
                    "que tu aies voulu",
                    "qu'il ait voulu/qu'elle ait voulu",
                    "que nous ayons voulu",
                    "que vous ayez voulu",
                    "qu'ils aient voulu/qu'elles aient voulu"
                ]
            ]
        ],
        [
            # 명령법 (Impératif)

                # 현재 (Présent)

                    "(tu) veuille",
                    "(nous) voulons",
                    "(vous) veuillez"


        ],
        [
            # 분사 (Participe)
            [
                # 현재 (Présent)
                "voulant"
            ],
            [
                # 과거 (Passé)

                    "voulu",
                    "voulue",
                    "voulus",
                    "voulues"

            ]
        ]
    ],
    "venir": [
        [
            # 직설법 (Indicatif)
            [
                # 현재 (Présent)

                    "je viens",
                    "tu viens",
                    "il vient/elle vient",
                    "nous venons",
                    "vous venez",
                    "ils viennent/elles viennent"

            ],
            # 과거
            [
                # 복합과거 (Passé composé)
                [
                    "je suis venu(e)",
                    "tu es venu(e)",
                    "il est venu/elle est venue",
                    "nous sommes venus/venues",
                    "vous êtes venus/venues",
                    "ils sont venus/elles sont venues"
                ],
                # 반과거 (Imparfait)
                [
                    "je venais",
                    "tu venais",
                    "il venait/elle venait",
                    "nous venions",
                    "vous veniez",
                    "ils venaient/elles venaient"
                ],
                # 대과거 (Plus-que-parfait)
                [
                    "j'étais venu(e)",
                    "tu étais venu(e)",
                    "il était venu/elle était venue",
                    "nous étions venus/venues",
                    "vous étiez venus/venues",
                    "ils étaient venus/elles étaient venues"
                ],
                # 단순과거 (Passé simple)
                [
                    "je vins",
                    "tu vins",
                    "il vint/elle vint",
                    "nous vînmes",
                    "vous vîntes",
                    "ils vinrent/elles vinrent"
                ],
                # 전과거 (Passé antérieur)
                [
                    "je fus venu(e)",
                    "tu fus venu(e)",
                    "il fut venu/elle fut venue",
                    "nous fûmes venus/venues",
                    "vous fûtes venus/venues",
                    "ils furent venus/elles furent venues"
                ]
            ],
            # 미래
            [
                # 단순미래 (Futur)
                [
                    "je viendrai",
                    "tu viendras",
                    "il viendra/elle viendra",
                    "nous viendrons",
                    "vous viendrez",
                    "ils viendront/elles viendront"
                ],
                # 근접미래 (Futur proche)
                [
                    "je vais venir",
                    "tu vas venir",
                    "il va venir/elle va venir",
                    "nous allons venir",
                    "vous allez venir",
                    "ils vont venir/elles vont venir"
                ],
                # 전미래 (Futur antérieur)
                [
                    "je serai venu(e)",
                    "tu seras venu(e)",
                    "il sera venu/elle sera venue",
                    "nous serons venus/venues",
                    "vous serez venus/venues",
                    "ils seront venus/elles seront venues"
                ]
            ]
        ],
        [
            # 조건법 (Conditionnel)
            [
                # 현재 (Présent)

                    "je viendrais",
                    "tu viendrais",
                    "il viendrait/elle viendrait",
                    "nous viendrions",
                    "vous viendriez",
                    "ils viendraient/elles viendraient"

            ],
            # 과거
            [
                # 형태 1
                [
                    "je serais venu(e)",
                    "tu serais venu(e)",
                    "il serait venu/elle serait venue",
                    "nous serions venus/venues",
                    "vous seriez venus/venues",
                    "ils seraient venus/elles seraient venues"
                ],
                # 형태 2
                [
                    "je fusse venu(e)",
                    "tu fusses venu(e)",
                    "il fût venu/elle fût venue",
                    "nous fussions venus/venues",
                    "vous fussiez venus/venues",
                    "ils fussent venus/elles fussent venues"
                ]
            ]
        ],
        [
            # 접속법 (Subjonctif)
            [
                # 현재 (Présent)

                    "que je vienne",
                    "que tu viennes",
                    "qu'il vienne/qu'elle vienne",
                    "que nous venions",
                    "que vous veniez",
                    "qu'ils viennent/qu'elles viennent"

            ],
            # 과거
            [
                # 반과거 (Imparfait)
                [
                    "que je vinsse",
                    "que tu vinsses",
                    "qu'il vînt/qu'elle vînt",
                    "que nous vînmes",
                    "que vous vîntes",
                    "qu'ils vinssent/qu'elles vinssent"
                ],
                # 대과거 (Plus-que-parfait)
                [
                    "que je fusse venu(e)",
                    "que tu fusses venu(e)",
                    "qu'il fût venu/elle fût venue",
                    "que nous fussions venus/venues",
                    "que vous fussiez venus/venues",
                    "qu'ils fussent venus/elles fussent venues"
                ],
                # 과거 (Passé)
                [
                    "que je sois venu(e)",
                    "que tu sois venu(e)",
                    "qu'il soit venu/elle soit venue",
                    "que nous soyons venus/venues",
                    "que vous soyez venus/venues",
                    "qu'ils soient venus/elles soient venues"
                ]
            ]
        ],
        [
            # 명령법 (Impératif)

                # 현재 (Présent)

                    "(tu) viens",
                    "(nous) venons",
                    "(vous) venez"


        ],
        [
            # 분사 (Participe)
            [
                # 현재 (Présent)
                "venant"
            ],
            [
                # 과거 (Passé)

                    "venu",
                    "venue",
                    "venus",
                    "venues"

            ]
        ]
    ],
    "falloir": [
        [
            # 직설법 (Indicatif)
            [
                # 현재 (Présent)

                    "il faut"

            ],
            # 과거
            [
                # 복합과거 (Passé composé)
                [
                    "il a fallu"
                ],
                # 반과거 (Imparfait)
                [
                    "il fallait"
                ],
                # 대과거 (Plus-que-parfait)
                [
                    "il avait fallu"
                ],
                # 단순과거 (Passé simple)
                [
                    "il fallut"
                ],
                # 전과거 (Passé antérieur)
                [
                    "il eut fallu"
                ]
            ],
            # 미래
            [
                # 단순미래 (Futur)
                [
                    "il faudra"
                ],
                # 근접미래 (Futur proche)
                [
                    "il va falloir"
                ],
                # 전미래 (Futur antérieur)
                [
                    "il aura fallu"
                ]
            ]
        ],
        [
            # 조건법 (Conditionnel)
            [
                # 현재 (Présent)

                    "il faudrait"

            ],
            # 과거
            [
                # 형태 1
                [
                    "il aurait fallu"
                ],
                # 형태 2
                [
                    "il eût fallu"
                ]
            ]
        ],
        [
            # 접속법 (Subjonctif)
            [
                # 현재 (Présent)

                    "qu'il faille"

            ],
            # 과거
            [
                # 반과거 (Imparfait)
                [
                    "qu'il fallût"
                ],
                # 대과거 (Plus-que-parfait)
                [
                    "qu'il eût fallu"
                ],
                # 과거 (Passé)
                [
                    "qu'il ait fallu"
                ]
            ]
        ],
        [
            # 명령법 (Impératif)

                # 현재 (Présent)

                    "il faut"


        ]
    ],
    "devoir": [
        [
            # 직설법 (Indicatif)
            [
                # 현재 (Présent)

                    "je dois",
                    "tu dois",
                    "il doit/elle doit",
                    "nous devons",
                    "vous devez",
                    "ils doivent/elles doivent"

            ],
            # 과거
            [
                # 복합과거 (Passé composé)
                [
                    "j'ai dû",
                    "tu as dû",
                    "il a dû/elle a dû",
                    "nous avons dû",
                    "vous avez dû",
                    "ils ont dû/elles ont dû"
                ],
                # 반과거 (Imparfait)
                [
                    "je devais",
                    "tu devais",
                    "il devait/elle devait",
                    "nous devions",
                    "vous deviez",
                    "ils devaient/elles devaient"
                ],
                # 대과거 (Plus-que-parfait)
                [
                    "j'avais dû",
                    "tu avais dû",
                    "il avait dû/elle avait dû",
                    "nous avions dû",
                    "vous aviez dû",
                    "ils avaient dû/elles avaient dû"
                ],
                # 단순과거 (Passé simple)
                [
                    "je dus",
                    "tu dus",
                    "il dut/elle dut",
                    "nous dûmes",
                    "vous dûtes",
                    "ils durent/elles durent"
                ],
                # 전과거 (Passé antérieur)
                [
                    "j'eus dû",
                    "tu eus dû",
                    "il eut dû/elle eut dû",
                    "nous eûmes dû",
                    "vous eûtes dû",
                    "ils eurent dû/elles eurent dû"
                ]
            ],
            # 미래
            [
                # 단순미래 (Futur)
                [
                    "je devrai",
                    "tu devras",
                    "il devra/elle devra",
                    "nous devrons",
                    "vous devrez",
                    "ils devront/elles devront"
                ],
                # 근접미래 (Futur proche)
                [
                    "je vais devoir",
                    "tu vas devoir",
                    "il va devoir/elle va devoir",
                    "nous allons devoir",
                    "vous allez devoir",
                    "ils vont devoir/elles vont devoir"
                ],
                # 전미래 (Futur antérieur)
                [
                    "j'aurai dû",
                    "tu auras dû",
                    "il aura dû/elle aura dû",
                    "nous aurons dû",
                    "vous aurez dû",
                    "ils auront dû/elles auront dû"
                ]
            ]
        ],
        [
            # 조건법 (Conditionnel)
            [
                # 현재 (Présent)

                    "je devrais",
                    "tu devrais",
                    "il devrait/elle devrait",
                    "nous devrions",
                    "vous devriez",
                    "ils devraient/elles devraient"

            ],
            # 과거
            [
                # 형태 1
                [
                    "j'aurais dû",
                    "tu aurais dû",
                    "il aurait dû/elle aurait dû",
                    "nous aurions dû",
                    "vous auriez dû",
                    "ils auraient dû/elles auraient dû"
                ],
                # 형태 2
                [
                    "j'eusse dû",
                    "tu eusses dû",
                    "il eût dû/elle eût dû",
                    "nous eussions dû",
                    "vous eussiez dû",
                    "ils eussent dû/elles eussent dû"
                ]
            ]
        ],
        [
            # 접속법 (Subjonctif)
            [
                # 현재 (Présent)

                    "que je doive",
                    "que tu doives",
                    "qu'il doive/qu'elle doive",
                    "que nous devions",
                    "que vous deviez",
                    "qu'ils doivent/qu'elles doivent"

            ],
            # 과거
            [
                # 반과거 (Imparfait)
                [
                    "que je dusse",
                    "que tu dusses",
                    "qu'il dût/qu'elle dût",
                    "que nous dussions",
                    "que vous dussiez",
                    "qu'ils dussent/qu'elles dussent"
                ],
                # 대과거 (Plus-que-parfait)
                [
                    "que j'eusse dû",
                    "que tu eusses dû",
                    "qu'il eût dû/qu'elle eût dû",
                    "que nous eussions dû",
                    "que vous eussiez dû",
                    "qu'ils eussent dû/qu'elles eussent dû"
                ],
                # 과거 (Passé)
                [
                    "que j'aie dû",
                    "que tu aies dû",
                    "qu'il ait dû/qu'elle ait dû",
                    "que nous ayons dû",
                    "que vous ayez dû",
                    "qu'ils aient dû/qu'elles aient dû"
                ]
            ]
        ],
        [
            # 명령법 (Impératif)

                # 현재 (Présent)

                    "(tu) dois",
                    "(nous) devons",
                    "(vous) devez"


        ],
        [
            # 분사 (Participe)
            [
                # 현재 (Présent)
                "devant"
            ],
            [
                # 과거 (Passé)

                    "dû",
                    "due",
                    "dus",
                    "dues"

            ]
        ]
    ]



}

print("\n안녕하세요,\n프랑스어 학습자를 위한 동사 변화 검색 사전 \ndict_conjugaison입니다 :)\n\n")
while True:
    verb = input('''
============dict_conjugaison============

찾으시려는 동사의 원형을 입력한 후
return 키를 눌러주세요

** 어휘 목록 **
Être, Avoir, Faire, Dire,
Pouvoir, Aller, Voir, Savoir,
Vouloir, Venir, Falloir, Devoir

* 악센트
àüûùœôïîêëèéçæâà

    q: 종료
========================================
    ''')
    verb = verb.strip()
    verb = verb.lower()
    if verb == 'q':
        break
    #사전에 있다
    if verb in d.keys():
        #용법입력
        usage = input('''
========================================
용법을 선택해주세요(숫자 입력 후 리턴)

    1. 직설법(Indicatif)
    2. 조건법(Conditionnel)
    3. 접속법(Subjonctif)
    4. 명령법(Imperatif)
    5. 분사(Participe)

    q: 종료
========================================
''')
        if usage == 'q':
            break
        if usage.isnumeric():
            usage = int(usage)-1
        else:
            print('잘못된 입력입니다.')
            input('처음으로 돌아가기 위해 리턴 키를 눌러주세요')
            continue
        #직설법
        if usage == 0:
            #시제입력
            tense = input('''
========================================
시제의 범위를 선택해주세요(숫자 입력 후 리턴)

    1. 현재(Présent)
    2. 과거(Passé)
    3. 미래(Futur)

    q: 종료
=====================================================
''')
            if tense == 'q':
                break
            if tense.isnumeric():
                tense = int(tense)-1
            else:
                print('잘못된 입력입니다.')
                input('처음으로 돌아가기 위해 리턴 키를 눌러주세요')
                continue
            #현재
            if tense == 0:

                print(f'''
=====================================================

{verb}의 {use[usage]}{ind[tense]}형 동사 변화입니다 :)
                ''')


                for i in d[verb][usage][tense]:
                    print(i)
                print('_________________________________________')
                input('처음으로 돌아가기 위해 리턴 키를 눌러주세요')
            #과거
            elif tense == 1:
                tense2 = input('''
========================================
상세 시제를 선택해주세요(숫자 입력 후 리턴)

    1. 복합과거(Passé composé)
    2. 반과거(Imparfait)
    3. 대과거(Plus-que-parfait)
    4. 단순과거(Passé simple)
    5. 전과거(Passé antérieur)

    q: 종료
=====================================================
''')
                if tense2 == 'q':
                    break
                if tense2.isnumeric():
                    tense2 = int(tense2)-1
                else:
                    print('잘못된 입력입니다.')
                    input('처음으로 돌아가기 위해 리턴 키를 눌러주세요')
                    continue
                print(f'''
=====================================================

{verb}의 {use[usage]}{ind[tense][tense2]}형 동사 변화입니다 :)
                ''')
                for i in d[verb][usage][tense][tense2]:
                    print(i)
                print('_________________________________________')
                input('처음으로 돌아가기 위해 리턴 키를 눌러주세요')
            #미래
            elif tense == 2:
                tense2 = input('''
=====================================================
상세 시제를 선택해주세요(숫자 입력 후 리턴)

    1. 단순미래(Futur simple)
    2. 근접미래(Futur proche)
    3. 전미래(Futur antérieur)

    q: 종료
=====================================================
''')
                if tense2 == 'q':
                    break
                if tense2.isnumeric():
                    tense2 = int(tense2)-1
                else:
                    print('잘못된 입력입니다.')
                    input('처음으로 돌아가기 위해 리턴 키를 눌러주세요')
                    continue
                print(f'''
=====================================================

{verb}의 {use[usage]}{ind[tense][tense2]}형 동사 변화입니다 :)
                ''')
                for i in d[verb][usage][tense][tense2]:
                    print(i)
                print('_________________________________________')
                input('처음으로 돌아가기 위해 리턴 키를 눌러주세요')
            else:
                print('잘못된 입력입니다.')
                input('처음으로 돌아가기 위해 리턴 키를 눌러주세요')
                continue
        #조건법
        elif usage == 1:
            #시제입력
            tense = input('''
========================================
시제의 범위를 선택해주세요(숫자 입력 후 리턴)

    1. 현재(Présent)
    2. 복합과거(Passé composé)

    q: 종료
========================================
''')
            if tense == 'q':
                break
            if tense.isnumeric():
                tense = int(tense)-1
            else:
                print('잘못된 입력입니다.')
                input('처음으로 돌아가기 위해 리턴 키를 눌러주세요')
                continue
            #현재
            if tense == 0:
                print(f'''
_________________________________________
{verb}의 {use[usage]}{con[tense]}형 동사 변화입니다 :)
    ''')
                for i in d[verb][usage][tense]:
                    print(i)
                print('_________________________________________')
                input('처음으로 돌아가기 위해 리턴 키를 눌러주세요')
            #과거
            elif tense == 1:
                tense2 = input('''
========================================
상세 시제를 선택해주세요(숫자 입력 후 리턴)

    1. 형태 1(Passé première forme)
    2. 형태 2(Passé deuxième forme))

    q: 종료
========================================
''')
                if tense2 == 'q':
                    break
                tense2 = int(tense2)-1
                print(f'''
_________________________________________
{verb}의 {use[usage]}{con[tense][tense2]}형 동사 변화입니다 :)
                ''')
                for i in d[verb][usage][tense][tense2]:
                    print(i)
                print('_________________________________________')
                input('처음으로 돌아가기 위해 리턴 키를 눌러주세요')
            else:
                print('잘못된 입력입니다.')
                input('처음으로 돌아가기 위해 리턴 키를 눌러주세요')
                continue
        #접속법
        elif usage == 2:
            tense = input('''
========================================
시제의 범위를 선택해주세요(숫자 입력 후 리턴)

    1. 현재(Présent)
    2. 과거(Passé)

    q: 종료
========================================
''')
            if tense == 'q':
                break
            if tense.isnumeric():
                tense = int(tense)-1
            else:
                print('잘못된 입력입니다.')
                input('처음으로 돌아가기 위해 리턴 키를 눌러주세요')
                continue
            #현재
            if tense == 0:
                print(f'''
_________________________________________
{verb}의 {use[usage]}{sub[tense]}형 동사 변화입니다 :)
                ''')
                for i in d[verb][usage][tense]:
                    print(i)
                print('_________________________________________')
                input('처음으로 돌아가기 위해 리턴 키를 눌러주세요')
            #과거
            elif tense == 1:
                tense2 = input('''
========================================
상세 시제를 선택해주세요(숫자 입력 후 리턴)


    1. 반과거(Imparfait)
    2. 대과거(Plus-que-parfait)
    3. 과거(Passé)

    q: 종료
========================================
''')
                if tense2 == 'q':
                    break
                if tense2.isnumeric():
                    tense2 = int(tense2)-1
                else:
                    print('잘못된 입력입니다.')
                    input('처음으로 돌아가기 위해 리턴 키를 눌러주세요')
                    continue
                print(f'''
=====================================================

{verb}의 {use[usage]}{sub[tense][tense2]}형 동사 변화입니다 :)
                ''')
                for i in d[verb][usage][tense][tense2]:
                    print(i)
                print('_________________________________________')
                input('처음으로 돌아가기 위해 리턴 키를 눌러주세요')
            else:
                print('잘못된 입력입니다.')
                input('처음으로 돌아가기 위해 리턴 키를 눌러주세요')
                continue
        #명령법
        elif usage == 3:
            print(f'''
=====================================================

{verb}의 {use[usage]}형 동사 변화입니다 :)
            ''')
            for i in d[verb][usage]:
                print(i)
            print('_________________________________________')
            input('처음으로 돌아가기 위해 리턴 키를 눌러주세요')
        #분사
        elif usage == 4:
            #시제입력
            tense = input('''
=====================================================
시제의 범위를 선택해주세요(숫자 입력 후 리턴)

    1. 현재(Présent)
    2. 과거(Passé)

    q: 종료
=====================================================
''')
            if tense == 'q':
                break
            if tense.isnumeric():
                tense = int(tense)-1
            else:
                print('잘못된 입력입니다.')
                input('처음으로 돌아가기 위해 리턴 키를 눌러주세요')
                continue
            print(f'''
=====================================================

{verb}의 {part[tense]}시제 분사입니다 :)
                ''')
            for i in d[verb][usage][tense]:
                    print(i)
            print('_________________________________________')
            input('처음으로 돌아가기 위해 리턴 키를 눌러주세요')

    #사전에 없다
    else:
        print('사전에 없는 단어입니다.')
        input('처음으로 돌아가기 위해 리턴 키를 눌러주세요')
        continue